### ISSUE TITLE
Estimate probability of infection based on symptoms and other data

### ISSUE THREAD

**Issue by matjaeck** [wirewirewirewire/pandoa#16]
We can't rely on test results as tests will not be available in big numbers and probably be reserved for emergency cases. 

> Man wird irgendwann Verdachtsfälle nur anhand von Symptomen melden und sich dann auch in den Statistiken mehr daran orientieren. Gleichzeitig wird man die Tests, die man hat, auf Risikogruppen fokussieren müssen.

https://www.zeit.de/wissen/gesundheit/2020-03/christian-drosten-coronavirus-pandemie-deutschland-virologe-charite?page=5#comments

So we need to think of a model how to calculate the probability. We could 
- use checkboxes with known common symptoms
- let the user add a rating how strong these symptoms are (helpful?)
- add "Shortcuts" like "Is one of the person in your household infected?" which when accpeted automatically mean that we consider this user as infected.
- ...

**Comment by br1sc** [comment]
lets base an estimation on the pandemic footprint index and a transitive and fast contact-sharing in case of an infection. if  i met 10 people who met 20 infected, my own  pandemic footprint index will raise.

**Comment by valentinriedl** [comment]
the simplest solution right now and working in China/S.Korea is taking your body temp twice a day. This is a reliable measure that you can expect to be regularly performed by each individual and rather specific for COVID, particularly in Germany outside the regular influenca period. 

One could include more sophisticated SIR-models at a later stage, i guess

**Comment by Hans-rooom** [comment]
we should use the body temp and add information (shortness of breath, dry cough,...)
Simply 3-4 symptoms that can be ticked off. It certainly can't hurt to gather this data. It is only important that there are not too many points.

We also need to know if the user is in quarantine (and why), and if someone in the vicinity is in quarantine and why.
